config/routes.rb
AnagramFinderApp::Application.routes.draw do
  get "anagrams/create"

  get "anagrams/destroy"

  resources :uploads do
    resources :anagrams
  end

end

app/models/anagram.rb
class Anagram < ActiveRecord::Base
	belongs_to :upload

	# Aim: 	Given a word, return all possible variable-length 
	# 		combinations of this word
	# param: word ##spawn my minions
	# TODO: Rename vars and class appropriately
	def word_combos(word)
		word = word.chars.to_a
		all_word_combo = []
		i = 1
		while i <= word.size
			all_word_combo << word.permutation(i).to_a
			i+=1
		end
		return all_word_combo
	end

	# Aim: Convert all word combos to strings. 
	# params: perms = is an array of arrays where 
	# 		  the first element contains all one-letter "words", 
	# 			the second element contains all two-letter "words", 
	# 			and so on and so forth
	# returns: true_perms
	# return type: Array
	def word_combos_to(all_word_combo)
		true_perms = all_word_combo.flatten(1)
		return true_perms.map {|x| x.join}
	end

	# Aim: Size of the 
	def permutation_size(word)
		n=word.size
		r=0
		while r<=n
			n.factorial/(n-r).factorial
			r+=1
		end
	end

	# Aim: Calculate the factorial of a given number
	# param(s): n = the number whose factorial is to be calculated
	# returns: n! = factorial of n
	# note: refactor factorial function. Put into a mathematical model
	def factorial
		(1..self).reduce(:*)
	end


	def find_all_anagrams(all_word_combo, dictionary)
		return all_word_combo & dictionary
	end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	has_many :anagrams

	FILE_STORE = "./upload/dictionary_files/"

	# Aim: Reads a dictionary File
	# Params: path=file path of the file to be read, expecting a textfile
	# TODO: Remove default path
	def readfile(path)
		dictionary_entry = IO.readlines(path) if File::exists?(path)
		return dictionary_entry.map {|x| x.delete "\n"}  #remove newline characters
	end

	# Aim: Write the contents of an uploaded file to the file storage directory
	def write_uploaded_file(uploaded_file, data)
		# create directory unless it already exists
		FileUtils.mkpath FILE_STORE.to_s unless File.directory?(FILE_STORE)

		#define file storage path
		filename = data['filename']
		path = File.join(FILE_STORE, filename)

		# write the file
		File.open(path, "wb") { |file| file.write(uploaded_file.read) }
	end
end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  
  # before_filter :set_anagram_result
  helper_method :anagram_result

  def create
  	@upload = Upload.find(params[:upload_id])
  	@anagram = @upload.anagrams.build(params[:anagram])

    # generate the permutation of all combinations of the given word
    all_word_combo = @anagram.word_combos(@anagram.word)

    # convert the complex array result to a level-1 flattened array of strings
    all_word_combo = @anagram.word_combos_to(all_word_combo)

    # get the list of loaded dictionary words
    path = Upload::FILE_STORE + @upload.filename
    dictionary = @upload.readfile(path)

    # which of these permutations exists in the given dictionary
    
    # TODO Test time feature for Benchmark real timing
    time_taken = Benchmark.realtime do
      @anagram_result = @anagram.find_all_anagrams(all_word_combo, dictionary)
    end

    @anagram.time_taken = time_taken

    print "Time: #{time_taken}"
    print "Anagram Result: #{@anagram_result}"
    print "Dictionary: #{dictionary}"

  	@anagram.save
  	redirect_to @upload
  end

  def destroy
  	@anagram = Anagram.find(params[:id])
  	@anagram.destroy

  	redirect_to @anagram.upload
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json

  # helper_method :file_loading_time, 
  #               :anagram_dictionary_duration, 
  #               :anagram_result

  helper_method :set_file_loading_time

  def anagram_dictionary_duration
    anagram_dictionary_duration
  end

  def anagram_result
    anagram_result
  end

  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    # get attribute values from param, manually
    filename = params[:upload][:uploaded_file].original_filename
    filetype = params[:upload][:uploaded_file].content_type
    file     = params[:upload][:uploaded_file].tempfile
    
    @upload = Upload.new(:filename => filename, :filetype => filetype)

    data = {'filename' => @upload.filename}

    # save file (+Benchmark)
    @loading_time = Benchmark.realtime do
      @upload.write_uploaded_file(file, data)
    end

    @loading_time.set_file_loading_time

    print "Loading Time: #{@loading_time}"

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render json: @upload, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

private
  def set_file_loading_time
    loading_time = @loading_time
  end
end

app/helpers/anagrams_helper.rb
module AnagramsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/anagrams/create.html.erb
<h1>Anagrams#create</h1>
<p>Find me in app/views/anagrams/create.html.erb</p>

app/views/anagrams/destroy.html.erb
<h1>Anagrams#destroy</h1>
<p>Find me in app/views/anagrams/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnagramFinderApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container"><%= yield %></div>


</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :uploaded_file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Anagram Finder App</h1>

<% @uploads.each do |upload| %>
  <h2> <%=link_to upload.filename, upload %> </h2>
<% end %>

<br />

<%= link_to 'New Upload', new_upload_path, :class => 'btn' %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to @upload.filename, @upload %></h1>
Loaded in: <%= set_file_loading_time %>

<h2>Anagrams</h2>
	<%= form_for [@upload, @upload.anagrams.build] do |f| %>
		<%= f.text_field :word %>
		<%= f.submit "Go" %>
	<% end %>

	<div class="row">
		<div class="span4">
			<% @upload.anagrams.each do |anagram| %>
			<p>
				<p><%= anagram.created_at %> </p>
				>:
				<%=  %> anagrams found for "<%= anagram.word %>" in ..
				<p>  <%=  %></p>
				<p><%= link_to "Remove", [@upload, anagram], :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-secondary'%></p>
			</br>
			</p> 
		<% end %>
		</div>
	</div>
	
</br>
<div class="form-actions">
	<%= link_to 'Back', uploads_path, :class => 'btn' %>
	|
	<%= link_to 'Edit', edit_upload_path(@upload), :class => 'btn' %> 
	|
	<%= link_to "Delete", @upload, :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger'%>
</div>